name: Fly.io Keep-Alive Ping

# Run every 10 minutes to prevent cold starts
on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch: {}  # Allow manual trigger for testing

jobs:
  ping-flyio:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Production API
        run: curl -fsS https://rohan-backend-api.fly.dev/health || echo "Ping failed"
